import { MD3Typescale } from "react-native-paper/lib/typescript/types";

export const CustomTypography: MD3Typescale = {
  displayLarge: {
    fontFamily: "Outfit-Bold",
    fontWeight: "700" as const,
    fontSize: 57,
    lineHeight: 64,
    letterSpacing: 0,
  },
  displayMedium: {
    fontFamily: "Outfit-SemiBold",
    fontWeight: "600" as const,
    fontSize: 45,
    lineHeight: 52,
    letterSpacing: 0,
  },
  displaySmall: {
    fontFamily: "Outfit-Medium",
    fontWeight: "500" as const,
    fontSize: 36,
    lineHeight: 44,
    letterSpacing: 0,
  },
  headlineLarge: {
    fontFamily: "Outfit-Bold",
    fontWeight: "700" as const,
    fontSize: 32,
    lineHeight: 40,
    letterSpacing: 0,
  },
  headlineMedium: {
    fontFamily: "Outfit-SemiBold",
    fontWeight: "600" as const,
    fontSize: 28,
    lineHeight: 36,
    letterSpacing: 0,
  },
  headlineSmall: {
    fontFamily: "Outfit-Medium",
    fontWeight: "500" as const,
    fontSize: 24,
    lineHeight: 32,
    letterSpacing: 0,
  },
  titleLarge: {
    fontFamily: "Outfit-SemiBold",
    fontWeight: "600" as const,
    fontSize: 22,
    lineHeight: 28,
    letterSpacing: 0,
  },
  titleMedium: {
    fontFamily: "Outfit-Medium",
    fontWeight: "500" as const,
    fontSize: 16,
    lineHeight: 24,
    letterSpacing: 0.15,
  },
  titleSmall: {
    fontFamily: "Outfit-Regular",
    fontWeight: "400" as const,
    fontSize: 14,
    lineHeight: 20,
    letterSpacing: 0.1,
  },
  bodyLarge: {
    fontFamily: "LeagueSpartan-Bold",
    fontWeight: "700" as const,
    fontSize: 16,
    lineHeight: 24,
    letterSpacing: 0.5,
  },
  bodyMedium: {
    fontFamily: "LeagueSpartan-Medium",
    fontWeight: "500" as const,
    fontSize: 14,
    lineHeight: 20,
    letterSpacing: 0.25,
  },
  bodySmall: {
    fontFamily: "LeagueSpartan-Regular",
    fontWeight: "400" as const,
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 0.4,
  },
  labelLarge: {
    fontFamily: "LeagueSpartan-SemiBold",
    fontWeight: "600" as const,
    fontSize: 14,
    lineHeight: 20,
    letterSpacing: 0.1,
  },
  labelMedium: {
    fontFamily: "LeagueSpartan-Medium",
    fontWeight: "500" as const,
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 0.5,
  },
  labelSmall: {
    fontFamily: "LeagueSpartan-Regular",
    fontWeight: "400" as const,
    fontSize: 11,
    lineHeight: 16,
    letterSpacing: 0.5,
  },
  default: {
    fontFamily: "Outfit-Regular",
    fontWeight: "400" as const,
    letterSpacing: 0,
  },
};
